name: Deploy to Firebase

on:
  push:
    branches:
      - main # Chạy workflow khi có đẩy mã lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # hoặc phiên bản node phù hợp với dự án của bạn

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v13.10.0
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.WEDDING_PHOTOS_ALBUM_ACTIONS_SECRETS }}
